### ISSUE TITLE
API to get the time associated with custom tags. 

### ISSUE THREAD

**Issue by HardikThakkar** [Comcast/mamba#29]
Hi Mamba Team,

I am exploring the framework and it looks great for parsing custom tags in the HLS Playlists. Is there any existing API to get the time associated with each occurrence of a custom tag relevant to the first ts segment in the playlist? 

For example, while parsing the below playlist, the first appearance of MYCUSTOMTAG is at 0 seconds because there are no ts chunks before that and the second appearance is at 10.01 seconds in the playlist after 123.ts and 456.ts, each with 5.005 seconds duration. Is there a way to get this information programmatically?

#EXTM3U
#EXT-X-VERSION:6
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:11
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-MYCUSTOMTAG:ID="1", X-CUSTOM-ATTRIBUTE="VAL1"
#EXTINF:5.005,
123.ts
#EXTINF:5.005,
456.ts
#EXT-X-MYCUSTOMTAG:ID="2",X-CUSTOM-ATTRIBUTE="VAL2"
#EXTINF:5.005,
789.ts
#EXT-X-ENDLIST

**Comment by dcoufal** [comment]
Yes! This is possible. I'm assuming that this is for VOD from context. This doesn't really work for Live playlists, since the concept of absolute time is not really present there, FYI.

I'm describing this from memory, so please feel free to come back to this ticket to ask for clarification.

This is how I would do it in mamba:

(1) Make a custom `HLSTagDescriptor` that contains your `EXT-X-MYCUSTOMTAG` tag. You can look at `PantosTag` to see how to do this, and there are also examples in the unit tests. The important thing that you have to do is that `public func scope() -> HLSTagDescriptorScope` should return `.mediaSegment` for `EXT-X-MYCUSTOMTAG`. This tells mamba that your custom tag belongs with media segments and it will show up in the `mediaSegmentGroups` (described below!)

(2) You'll have to parse your playlist as usual, making sure to pass your custom `HLSTagDescriptor` in the initializer of `HLSParser` (i.e. `let parser = HLSParser(tagTypes:[MyCustomTagDescriptor.self]`)

(3) Once you have your parsed playlist, you can find your tags `let tags = playlist.tags.filter { $0.tagDescriptor == MyCustomTagDescriptor.myCustomTag }`. You also want the indices of each tag, so `let indices = tags.compactMap { playlist.tags.index(of: $0) }` <- assumes Swift 4.2

(4) Part of parsing a HLS playlist is dividing the playlist up into sections. There's a "header", a bunch of "media segment groups" and a "footer". We're interested in the "media segment groups".

A "media segment group" is minimally:

```
#EXTINF:5.005,
789.ts
```

Every "media segment group" is delimited by a `.Location` tag, which is the url (usually relative) of the media segment.

But if there are other tags that have `HLSTagDescriptorScope.mediaSegment` scope, and they are before the `.Location` tag, they will be put into the "media segment group", i.e.:

```
#EXT-X-MYCUSTOMTAG:ID="2",X-CUSTOM-ATTRIBUTE="VAL2" <- Part of this group
#EXTINF:5.005,
789.ts
```

"media segment group"s (which are `MediaSegmentTagGroup` in mamba code) have all kinds of useful properties, but for you you care that they have time info in them.

Given this, we can loop through the indices to get start and end times:

```
for index in indices {
  guard let timeRange = playlist.timeRange(forTagIndex: index) else {
    break
  }
  let startTime = timeRange.start
  let endTime = timeRange.end
  let duration = timeRange.duration
}
```

So, you can do anything you want with the start/end/duration of that segment.

Hope this helps!

**Comment by dcoufal** [comment]
Leaving this open. Ideally this would be in a playground as sample code as it's a pretty common use case.

**Comment by dcoufal** [comment]
Closing this in favor of #42
