### ISSUE TITLE
Latest Version Not on Cocoapods

### ISSUE THREAD

**Issue by jgainfort** [Comcast/mamba#35]
Latest Version Found on Cocoapods is 1.0.5 while the latest podspec shows 1.0.7. Maybe the pod push failed?

**Comment by jgainfort** [comment]
I tried updating myself and originally got this error:

> Command PhaseScriptExecution failed with a nonzero exit code

I fixed this error by upgrading to the latest beta version of Cocoapods

`sudo gem install cocoapods --pre`

Now I just get an error saying I am not an owner of the pod which is what I was expecting.

> [!] You (john@realeyes.com) are not allowed to push new versions for this pod. The owners of this pod are dcoufal@alum.mit.edu.

@dcoufal  can you please help out real quick?

**Comment by dcoufal** [comment]
Hi @jgainfort. I've been on holiday for a week, sorry for the wait! Just got in office.

1.0.6 missing is honestly just because I forgot for that release.

1.0.7 missing is due to a bug in cocoa pods where if you had Xcode 10 and the Xcode 10.1 beta installed at the same time, a change in some file format somewhere in 10.1 confused cocoa pods.

I'll update to release Xcode 10.1 and see if that fixes it. Sounds like it might already be fixed in a beta cocoa pods from your note so I can try that too.

I'll update and close this ticket when I'm done.

**Comment by jgainfort** [comment]
Sounds good. Thank you!

**Comment by dcoufal** [comment]
FWIW this is the cocoa pods issue. Looks like it was fixed.

https://github.com/CocoaPods/fourflusher/pull/11

**Comment by dcoufal** [comment]
OK, 1.0.7 is up now @jgainfort!
